const { GET_ALL_POSTS, GET_REPORTED_POSTS, GET_PROFILE_POSTS, BLOCK_POST, ADD_POST, DELETE_POST } = require("../../src/Post/postEndPoints");
const { BLOCK_USER_ACCOUNT, GET_USER_BY_ID, UPDATE_USER_PASSWORD, DEACTIVATE_USER_ACCOUNT, UPDATE_PROFILE_HANDLER, GET_ALL_USERS } = require("../../src/User/userEndPoints");



module.exports=[BLOCK_USER_ACCOUNT ,UPDATE_USER_PASSWORD ,GET_USER_BY_ID ,DEACTIVATE_USER_ACCOUNT ,UPDATE_PROFILE_HANDLER ,GET_ALL_POSTS , ADD_POST,
    GET_REPORTED_POSTS , GET_PROFILE_POSTS ,BLOCK_POST , DELETE_POST ,GET_ALL_USERS];

 
// exports.BLOCK_POST="user:BLOCK_POST";//ADMIN AND SUPER_ADMIN
// exports.DELETE_POST="user:DELETE_POST";//USER AND ADMIN 
// exports.GET_PROFILE_POSTS="user:GET_PROFILE_POSTS";//USER AND ADMIN
// exports.GET_ALL_POSTS="user:GET_ALL_POSTS";// ADMIN & SUPERaDMIN
// exports.GET_REPORTED_POSTS="user:GET_REPORTED_POSTS";//ADMIN & SUPER ADMIN

