const { ADD_POST, EDIT_POST, REPORT_POST, GET_PROFILE_POSTS, DELETE_POST, GET_ALL_USERS_POSTS } = require("../../src/Post/postEndPoints");
const { SIGN_UP, SIGN_IN, FORGET_PASSWORD, UPDATE_PROFILE_HANDLER, UPDATE_USER_PASSWORD,
     DEACTIVATE_USER_ACCOUNT } = require("../../src/User/userEndPoints");


module.exports=[SIGN_UP,SIGN_IN, FORGET_PASSWORD ,UPDATE_PROFILE_HANDLER , UPDATE_USER_PASSWORD, DEACTIVATE_USER_ACCOUNT ,ADD_POST , 
     EDIT_POST  , REPORT_POST,DELETE_POST ,GET_PROFILE_POSTS, GET_ALL_USERS_POSTS];
// "user:SIGN_UP";
// "user:SIGN_IN";
// "user:FORGET_PASSWORD";
// "user:UPDATE_PROFILE_HANDLER";
// "user:UPDATE_USER_PASSWORD";
// "user:DEACTIVATE_USER_ACCOUNT";

// "user:ADD_POST";//USER
// "user:EDIT_POST"; //USER
// "user:REPORT_POST";//USER
// "user:DELETE_POST";//USER AND ADMIN 
// "user:GET_PROFILE_POSTS";//USER AND ADMIN
// "user:GET_ALL_USERS_POSTS";//USERS